### PR TITLE
Fix integration api

### LINKED ISSUE #1864: [Bug] Changing Custom Fields using WS only works if using lower case names
If you create two custom fields, one using uppercase in any way and the other using only lower case, only the lower case can be changed using WebSocket.

This works as expected in v3 so there seems to have been some change in the v4 implementation.

Windows 10
OnTime 4.1.0

### PR DESCRIPTION
**Pull request by alex-Arc**
fixes #1864 
and allows changing flag and count to end from api

### CODE REVIEW

File: apps/server/src/api-integration/integration.controller.ts [hunk 1]
```diff
@@ -63,32 +70,76 @@ const actionHandlers: Record<ApiActionTag, ActionHandler> = {
...
-      const key = Object.keys(newObjectProperty)[0] as keyof OntimeEvent;
-      shouldThrottle = shouldThrottle || willCauseRegeneration(key);
-      if (patchEvent.custom && newObjectProperty.custom) {
-        Object.assign(patchEvent.custom, newObjectProperty.custom);
-      } else {
-        Object.assign(patchEvent, newObjectProperty);
-      }
-    });
+    if (isOntimeEvent(targetEntry)) {
+      assertIsEvent(patchEntry);
```
Comment (cpvalente) [inline apps/server/src/api-integration/integration.controller.ts]: question: would these assertions not fail since we dont have the type property?

File: apps/server/src/api-integration/integration.controller.ts [hunk 2]
```diff
@@ -63,32 +70,76 @@ const actionHandlers: Record<ApiActionTag, ActionHandler> = {
...
-      const newObjectProperty = parseProperty(property, value);
-      const key = Object.keys(newObjectProperty)[0] as keyof OntimeEvent;
-      shouldThrottle = shouldThrottle || willCauseRegeneration(key);
-      if (patchEvent.custom && newObjectProperty.custom) {
-        Object.assign(patchEvent.custom, newObjectProperty.custom);
-      } else {
-        Object.assign(patchEvent, newObjectProperty);
-      }
-    });
+    if (isOntimeEvent(targetEntry)) {
```
Comment (cpvalente) [inline apps/server/src/api-integration/integration.controller.ts]: suggestion: I think we want to avoid adding this complexity
can we instead say that we allow the mutation
if the property is whitelisted
if the property exists in the target entry

this should mean we can make things with less checks and more generic. ie: adding new types or fields doesnt mean changes here

File: apps/server/src/api-integration/integration.utils.ts [hunk 3]
```diff
@@ -41,19 +43,71 @@ const propertyConversion = {
   timeEnd: (value: unknown) => clampDuration(coerceNumber(value)),
 };
 
-export function parseProperty(property: string, value: unknown) {
+export function parseEventProperty(property: string, value: unknown) {
```
Comment (cpvalente) [inline apps/server/src/api-integration/integration.utils.ts]: question: I didnt understand the need to have different maps per entry type. The same property should have the same type in all entries, is that not right?

Comment (alex-Arc) [reply apps/server/src/api-integration/integration.utils.ts]: there are not timers in milestone and group
and the group has the targetDuration

File: apps/server/src/api-integration/integration.utils.ts [hunk 4]
```diff
@@ -36,14 +38,15 @@ const propertyConversion = {
...
   timeStrategy: (value: unknown) => coerceEnum<TimeStrategy>(value, TimeStrategy),
 
+  targetDuration: (value: unknown) => clampDuration(coerceNumber(value)), // only exist in the group
   duration: (value: unknown) => clampDuration(coerceNumber(value)),
   timeStart: (value: unknown) => clampDuration(coerceNumber(value)),
   timeEnd: (value: unknown) => clampDuration(coerceNumber(value)),
 };
 
-export function parseProperty(property: string, value: unknown) {
+export function parseEventProperty(property: string, value: unknown) {
```
Comment (cpvalente) [inline apps/server/src/api-integration/integration.utils.ts]: Since this doesnt relate to OntimeEvents, how about leaving it as it was or

```suggestion
export function parseEntryProperty(property: string, value: unknown) {
```

**Review by cpvalente — APPROVED** [review]
thank you, good stuff
